[package]
name = "tlm"
version = "0.1.0"
authors = ["Alexi Peck <alexinicolaspeck@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
regex = "1"
argparse = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"
diesel = { version = "1.4.7", features = ["postgres"] }
seahash = "4.1.0"
lazy_static = "1.4.0"
serde_json = "1.0.67"
ctrlc = "3.2.0"
tracing-appender = "0.1.2"
tracing-subscriber = "0.2.21"
tracing = "0.1.26"
rayon = "1.5.1"
