[package]
name = "tlm"
version = "0.1.0"
authors = ["Alexi Peck <alexinicolaspeck@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
regex = "1"
rand = "0.8.4"
argparse = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"
diesel = { version = "1.4.7", features = ["postgres"] }
seahash = "4.1.0"

[profile.release]
debug = true
