[package]
name = "tlm"
version = "0.1.0"
authors = ["Alexi Peck <alexinicolaspeck@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
regex = "1"
argparse = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"
diesel = { version = "1.4.7", features = ["postgres"] }
seahash = "4.1.0"
lazy_static = "1.4.0"
indicatif = "0.17.0-beta.1"
serde_json = "1.0.67"
ctrlc = "3.2.0"
websocket = "0.26.2"